package com.monitor.model;
// Generated 23/06/2017 12:40:03 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Query;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Campana generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "CAMPANA", schema = "MONITOR")
public class Campana  implements Serializable{

	private CampanaId id;
	private String nombre;
	private Date fechaalta;
	private Integer status;

	private Set<Sitio> sitios = new HashSet<Sitio>(0);

	public Campana() {
	}

	public Campana(CampanaId id) {
		this.id = id;
	}

	public Campana(CampanaId id, String nombre, Integer status, Set<Sitio> sitios) {
		this.id = id;
		this.nombre = nombre;
		this.status = status;
		this.sitios = sitios;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cveCampana", column = @Column(name = "CVE_CAMPANA", nullable = false, length = 12)),
			@AttributeOverride(name = "cveClipro", column = @Column(name = "CVE_CLIPRO", nullable = false, length = 10)) })
	public CampanaId getId() {
		return this.id;
	}

	public void setId(CampanaId id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "STATUS", precision = 6, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campana")
	public Set<Sitio> getSitios() {
		return this.sitios;
	}

	public void setSitios(Set<Sitio> sitios) {
		this.sitios = sitios;
	}

	public Date getFechaalta() {
		return fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

}
